#!/usr/bin/env python3
import sys
variable = 'value'
if 'Aye Captain' in variable: 
	print('True')
else: 
	print('Not True')
number =int(sys.argv[1]) 
if number>0: 
	print('positive')

if number == 0:
	print('this number is 0')
elif number >= 50: 
	print('this number is large than 50')
elif number % 2 == 0:
	print('this number issmaller than 50 and even')
else:
	print('this number is not even')

if number < 50 and number % 2 == 0: 
	print('this number is even and less than 50')
else: 
	print('not smaller than 50 or even')
